
Collecting tasks from: tasks.py
============================= Running: [96mvanna_demo[0m ==============================
[96mvanna_demo[0m status: [91mFAIL
[0m[91m
net::ERR_CONNECTION_REFUSED at http://localhost:8084/
[0m===================== Full Traceback (running [96mvanna_demo[0m) ======================
[91mTraceback (most recent call last):
  File "C:\ProgramData\robocorp\ht\971d110_b1f3c24_691db988\lib\site-packages\robocorp\tasks\_commands.py", line 430, in run
    result = task.run(*args, **kwargs)
  File "C:\ProgramData\robocorp\ht\971d110_b1f3c24_691db988\lib\site-packages\robocorp\tasks\_task.py", line 79, in run
    return self.method(*args, **kwargs)
  File "c:\Users\stefa\3AInformatica_Prjs\009.sensors_data_analysis\3AAI\tasks.py", line 19, in vanna_demo
    open_browser()
  File "c:\Users\stefa\3AInformatica_Prjs\009.sensors_data_analysis\3AAI\tasks.py", line 41, in open_browser
    browser.goto("http://localhost:8084")
  File "C:\ProgramData\robocorp\ht\971d110_b1f3c24_691db988\lib\site-packages\robocorp\browser\__init__.py", line 224, in goto
    p.goto(url)
  File "C:\ProgramData\robocorp\ht\971d110_b1f3c24_691db988\lib\site-packages\playwright\sync_api\_generated.py", line 9327, in goto
    self._sync(
  File "C:\ProgramData\robocorp\ht\971d110_b1f3c24_691db988\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
  File "C:\ProgramData\robocorp\ht\971d110_b1f3c24_691db988\lib\site-packages\playwright\_impl\_page.py", line 484, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\ProgramData\robocorp\ht\971d110_b1f3c24_691db988\lib\site-packages\playwright\_impl\_frame.py", line 149, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\ProgramData\robocorp\ht\971d110_b1f3c24_691db988\lib\site-packages\playwright\_impl\_connection.py", line 63, in send
    return await self._connection.wrap_api_call(
  File "C:\ProgramData\robocorp\ht\971d110_b1f3c24_691db988\lib\site-packages\playwright\_impl\_connection.py", line 495, in wrap_api_call
    return await cb()
  File "C:\ProgramData\robocorp\ht\971d110_b1f3c24_691db988\lib\site-packages\playwright\_impl\_connection.py", line 101, in inner_send
    result = next(iter(done)).result()
playwright._impl._errors.Error: net::ERR_CONNECTION_REFUSED at http://localhost:8084/

[0m================================================================================
Robocorp Log (html): c:\Users\stefa\3AInformatica_Prjs\009.sensors_data_analysis\3AAI\output\log.html
